/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ClienteDAO;
import dao.FornecedorDAO;
import dao.PeçaDAO;
import dao.VendaDAO;

/**
 *
 * @author Rogério e Octavio
 */
public class FormPricipal extends javax.swing.JFrame {
    
    public static FornecedorDAO daoFornecedor = null;
    public static PeçaDAO daoPeça = null;
    public static VendaDAO daoVenda = null;
     public static ClienteDAO daoCliente = null;

    /**
     * Creates new form formPricipal
     */
    public FormPricipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        daoFornecedor = new FornecedorDAO();
        daoPeça = new PeçaDAO();
        daoVenda = new VendaDAO();
        daoCliente = new ClienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemCadProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuItemConsClientes = new javax.swing.JMenuItem();
        jMenuItemConsProdutos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItemNovaVenda = new javax.swing.JMenuItem();
        jMenuItemEmitirNota = new javax.swing.JMenuItem();
        jMenuSuporte = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Controle de Estoque");
        setExtendedState(6);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoRogerio.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/add.png"))); // NOI18N
        jMenuCadastro.setText("Cadastros");

        jMenuItemCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/lorry.png"))); // NOI18N
        jMenuItemCadCliente.setText("Fornecedores");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadCliente);

        jMenuItemCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/wrench.png"))); // NOI18N
        jMenuItemCadProdutos.setText("Peças");
        jMenuItemCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdutosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadProdutos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/user.png"))); // NOI18N
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem1);
        jMenuCadastro.add(jSeparator1);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/door_out.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemSair);

        jMenuBar1.add(jMenuCadastro);

        jMenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/magnifier.png"))); // NOI18N
        jMenuConsulta.setText("Consultas");

        jMenuItemConsClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/lorry.png"))); // NOI18N
        jMenuItemConsClientes.setText("Fornecedores");
        jMenuItemConsClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsClientesActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsClientes);

        jMenuItemConsProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/wrench.png"))); // NOI18N
        jMenuItemConsProdutos.setText("Peças");
        jMenuItemConsProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsProdutosActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItemConsProdutos);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/user.png"))); // NOI18N
        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuItem2);

        jMenuBar1.add(jMenuConsulta);

        jMenuVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/cart.png"))); // NOI18N
        jMenuVenda.setText("Venda");
        jMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendaActionPerformed(evt);
            }
        });

        jMenuItemNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/cart_go.png"))); // NOI18N
        jMenuItemNovaVenda.setText("Nova Venda");
        jMenuItemNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaVendaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemNovaVenda);

        jMenuItemEmitirNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/text_padding_left.png"))); // NOI18N
        jMenuItemEmitirNota.setText("Emitir Nota Fiscal");
        jMenuItemEmitirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmitirNotaActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuItemEmitirNota);

        jMenuBar1.add(jMenuVenda);

        jMenuSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/user_comment.png"))); // NOI18N
        jMenuSuporte.setText("Suporte");

        jMenuItemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/help.png"))); // NOI18N
        jMenuItemAjuda.setText("Ajuda");
        jMenuSuporte.add(jMenuItemAjuda);
        jMenuSuporte.add(jSeparator2);

        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/book.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuSuporte.add(jMenuItemSobre);

        jMenuBar1.add(jMenuSuporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
        new FormFornecedor().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemConsClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsClientesActionPerformed
        // TODO add your handling code here:
       // new FormBuscarFornecedor().setVisible(true);
           new FormBuscarFornecedor1().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsClientesActionPerformed

    private void jMenuItemCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdutosActionPerformed
        // TODO add your handling code here:
        new FormPeças().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadProdutosActionPerformed

    private void jMenuItemConsProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsProdutosActionPerformed
        // TODO add your handling code here:
        new FormBuscarPeças().setVisible(true);
    }//GEN-LAST:event_jMenuItemConsProdutosActionPerformed

    private void jMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendaActionPerformed

    }//GEN-LAST:event_jMenuVendaActionPerformed

    private void jMenuItemNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaVendaActionPerformed
        // TODO add your handling code here:
        new FormVenda().setVisible(true);
    }//GEN-LAST:event_jMenuItemNovaVendaActionPerformed

    private void jMenuItemEmitirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmitirNotaActionPerformed
        // TODO add your handling code here:
        new FormEmitirNotaFiscal().setVisible(true);
    }//GEN-LAST:event_jMenuItemEmitirNotaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         new FormCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //new FormBuscarCliente().setVisible(true);
          new FormBuscarCliente1().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadProdutos;
    private javax.swing.JMenuItem jMenuItemConsClientes;
    private javax.swing.JMenuItem jMenuItemConsProdutos;
    private javax.swing.JMenuItem jMenuItemEmitirNota;
    private javax.swing.JMenuItem jMenuItemNovaVenda;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuSuporte;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
