/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Rogério e Octavio
 */
public class FormCliente extends javax.swing.JFrame {
public Cliente cliente = null;
    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstadoCivil = new javax.swing.ButtonGroup();
        lbCpf = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        abas = new javax.swing.JTabbedPane();
        PainelDados = new javax.swing.JPanel();
        lbTelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        painelEstado = new javax.swing.JPanel();
        rdSolteiro = new javax.swing.JRadioButton();
        rdCasado = new javax.swing.JRadioButton();
        rdDivorciado = new javax.swing.JRadioButton();
        rdUniao = new javax.swing.JRadioButton();
        rdViuvo = new javax.swing.JRadioButton();
        painelEndereço = new javax.swing.JPanel();
        tfLogradouro = new javax.swing.JTextField();
        lbLogradouro = new javax.swing.JLabel();
        lbComplemento = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lbCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JFormattedTextField();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCpf.setText("CPF:");
        getContentPane().add(lbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfActionPerformed(evt);
            }
        });
        getContentPane().add(tfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 112, -1));

        lbNome.setText("Nome Completo:");
        getContentPane().add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 330, -1));

        lbTelefone.setText("Telefone:");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbEmail.setText("Email:");

        painelEstado.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Civil"));

        bgEstadoCivil.add(rdSolteiro);
        rdSolteiro.setText("Solteiro");
        rdSolteiro.setActionCommand("Solteiro");

        bgEstadoCivil.add(rdCasado);
        rdCasado.setText("Casado");
        rdCasado.setActionCommand("Casado");

        bgEstadoCivil.add(rdDivorciado);
        rdDivorciado.setText("Divorciado");
        rdDivorciado.setActionCommand("Divorciado");

        bgEstadoCivil.add(rdUniao);
        rdUniao.setText("União Estável");
        rdUniao.setActionCommand("União Estável");
        rdUniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdUniaoActionPerformed(evt);
            }
        });

        bgEstadoCivil.add(rdViuvo);
        rdViuvo.setText("Viúvo");
        rdViuvo.setActionCommand("Viúvo");

        javax.swing.GroupLayout painelEstadoLayout = new javax.swing.GroupLayout(painelEstado);
        painelEstado.setLayout(painelEstadoLayout);
        painelEstadoLayout.setHorizontalGroup(
            painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdSolteiro)
                .addGap(18, 18, 18)
                .addComponent(rdCasado)
                .addGap(18, 18, 18)
                .addComponent(rdDivorciado)
                .addGap(18, 18, 18)
                .addComponent(rdUniao)
                .addGap(18, 18, 18)
                .addComponent(rdViuvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelEstadoLayout.setVerticalGroup(
            painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEstadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(painelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdSolteiro)
                    .addComponent(rdCasado)
                    .addComponent(rdDivorciado)
                    .addComponent(rdUniao)
                    .addComponent(rdViuvo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDadosLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTelefone)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(painelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(painelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        abas.addTab("Dados Pessoais", PainelDados);

        painelEndereço.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelEndereço.add(tfLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 519, -1));

        lbLogradouro.setText("Logradouro");
        painelEndereço.add(lbLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lbComplemento.setText("Complemento");
        painelEndereço.add(lbComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        painelEndereço.add(tfComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 263, -1));

        lbCidade.setText("Cidade");
        painelEndereço.add(lbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        painelEndereço.add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 193, -1));

        lbEstado.setText("Estado");
        painelEndereço.add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minas Gerais", "Rio de Janeiro", "São Paulo" }));
        painelEndereço.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 133, -1));

        lbCep.setText("CEP");
        painelEndereço.add(lbCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelEndereço.add(tfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 132, -1));

        abas.addTab("Endereço Completo", painelEndereço);

        getContentPane().add(abas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/user_add.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 40));

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/user_edit.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 40));

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/arrow_refresh.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, 40));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/door_out.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 100, 40));

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/magnifier.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdUniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdUniaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdUniaoActionPerformed

    private void tfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfActionPerformed

    
    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        
        // Criar o objeto e preenche-lo
        Cliente cliente = new Cliente();
        
        // Pegar os dados da tela
        cliente.setCpf(tfCpf.getText());
        cliente.setNome(tfNome.getText());
        cliente.setTelefone(tfTelefone.getText());
        cliente.setEmail(tfEmail.getText());
        cliente.setEstadoCivil(bgEstadoCivil.getSelection().getActionCommand());
        
        cliente.getEndereco().setLogradouro(tfLogradouro.getText());
        cliente.getEndereco().setComplemento(tfComplemento.getText());
        cliente.getEndereco().setCidade(tfCidade.getText());
        cliente.getEndereco().setEstado(cbEstado.getSelectedItem().toString());
        cliente.getEndereco().setCep(tfCep.getText());
        
        
        
        // Salvar na base de dados
        FormPricipal.daoCliente.adicionarCliente(cliente);
        JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso", "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
        
        limpar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void limpar(){
    
        tfCpf.setText("");
        tfNome.setText("");
        tfTelefone.setText("");
        tfEmail.setText("");
        bgEstadoCivil.clearSelection();
        
        abas.setSelectedIndex(0);
        
        tfLogradouro.setText("");
        tfComplemento.setText("");
        tfCidade.setText("");
        cbEstado.setSelectedIndex(-1);
        tfCep.setText("");
        
        tfCpf.requestFocus();
        
    }
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        String CPF = tfCpf.getText();
        Cliente cliente = FormPricipal.daoCliente.buscarCliente(CPF);
        tfNome.setText(cliente.getNome());
        tfTelefone.setText(cliente.getTelefone());
        tfEmail.setText(cliente.getEmail());
        // setar o estado civil nos campos radio
        JRadioButton radio;
        Enumeration en = bgEstadoCivil.getElements();
        while(en.hasMoreElements()){
            radio = (JRadioButton) en.nextElement();
            if(radio.getText().equals(cliente.getEstadoCivil()))
                radio.setSelected(true);
        }
        
        tfLogradouro.setText(cliente.getEndereco().getLogradouro());
        tfComplemento.setText(cliente.getEndereco().getComplemento());
        tfCidade.setText(cliente.getEndereco().getCidade());
        // setar cep no combobox
        for (int i = 0; i < cbEstado.getItemCount(); i++){
            if(cbEstado.getItemAt(i).equals(cliente.getEndereco().getEstado())){
                cbEstado.setSelectedItem(i);
            }
        }
        tfCep.setText(cliente.getEndereco().getCep());
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        // Criar o objeto e preenche-lo
        Cliente cliente = new Cliente();
        
        // Pegar os dados da tela
        cliente.setCpf(tfCpf.getText());
        cliente.setNome(tfNome.getText());
        cliente.setTelefone(tfTelefone.getText());
        cliente.setEmail(tfEmail.getText());
        cliente.setEstadoCivil(bgEstadoCivil.getSelection().getActionCommand());
        
        cliente.getEndereco().setLogradouro(tfLogradouro.getText());
        cliente.getEndereco().setComplemento(tfComplemento.getText());
        cliente.getEndereco().setCidade(tfCidade.getText());
        cliente.getEndereco().setEstado(cbEstado.getSelectedItem().toString());
        cliente.getEndereco().setCep(tfCep.getText());
        
        
        
        // Salvar na base de dados
        FormPricipal.daoCliente.alterarCliente(cliente);
        JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso", "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
        
        limpar();
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelDados;
    private javax.swing.JTabbedPane abas;
    private javax.swing.ButtonGroup bgEstadoCivil;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JPanel painelEndereço;
    private javax.swing.JPanel painelEstado;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdDivorciado;
    private javax.swing.JRadioButton rdSolteiro;
    private javax.swing.JRadioButton rdUniao;
    private javax.swing.JRadioButton rdViuvo;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
