/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Endereco;
import classes.Peça;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerim
 */
public class FormBuscarCliente1 extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
        public FormBuscarCliente1() {
        initComponents();
        
        this.modelo = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBuscarPeca = new javax.swing.JButton();
        cbBuscarTodas = new javax.swing.JCheckBox();
        lbCodigo = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btExclur = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Clientes");

        btBuscarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/wrench.png"))); // NOI18N
        btBuscarPeca.setText("Buscar Cliente");
        btBuscarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPecaActionPerformed(evt);
            }
        });

        cbBuscarTodas.setForeground(new java.awt.Color(0, 0, 204));
        cbBuscarTodas.setText("Buscar todas");
        cbBuscarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarTodasActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código");

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/pencil.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/door_out.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btExclur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/delete.png"))); // NOI18N
        btExclur.setText("Excluir");
        btExclur.setEnabled(false);
        btExclur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclurActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Email", "Telefone", "Estado Civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCodigo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscarPeca)
                                .addGap(60, 60, 60)
                                .addComponent(cbBuscarTodas))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEditar)
                        .addGap(109, 109, 109)
                        .addComponent(btExclur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscarPeca)
                    .addComponent(cbBuscarTodas)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btSair)
                    .addComponent(btExclur))
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(784, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPecaActionPerformed
        // TODO add your handling code here:
        limparTabela();
        
        if(cbBuscarTodas.isSelected()){ // buscar todos os livros
            
            List<Cliente> lista = FormPricipal.daoCliente.todosClientes();
            for(Cliente p: lista){
                incluirCliente(p);
            }
        }
        else{ // buscar um so
            
            if(tfCpf.getText().trim().length() != 0){
                
               String cpf = tfCpf.getText();
                Cliente cliente = FormPricipal.daoCliente.buscarCliente(cpf);
                if(cliente != null){
                    incluirCliente(cliente);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Cliente não encontrada", "Atenção", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Prencher o CPF", "Atenção", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btBuscarPecaActionPerformed

    private void cbBuscarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarTodasActionPerformed
        // TODO add your handling code here:
        if(cbBuscarTodas.isSelected()){
            tfCpf.setEnabled(false);
        }
        else{
            tfCpf.setEnabled(true);
            tfCpf.requestFocus();
            tfCpf.setText("");
        }
    }//GEN-LAST:event_cbBuscarTodasActionPerformed

    
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btExclurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclurActionPerformed
        // TODO add your handling code here:
        
        Cliente cliente = getCliente();
        FormPricipal.daoCliente.removerCliente(cliente.getCpf());
        
        modelo.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_btExclurActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        Cliente cliente = getCliente();
        
        FormCliente frm = new FormCliente();
        frm.setVisible(true);
        frm.cliente = cliente;
        this.dispose();
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        btEditar.setEnabled(true);
        btExclur.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void limparTabela(){
        for (int i = jTable1.getRowCount() - 1; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    private void incluirCliente(Cliente cliente){
        modelo.addRow(new Object[]{cliente.getCpf(), cliente.getNome(), cliente.getEmail(), cliente.getTelefone(),
            cliente.getEstadoCivil()});
        
    }
    
    private Cliente getCliente(){
        Cliente cliente = new Cliente();
        int linha = jTable1.getSelectedRow();
        
        cliente.setCpf((String) modelo.getValueAt(linha, 0));
        cliente.setNome((String) modelo.getValueAt(linha, 1));
        cliente.setEmail((String) modelo.getValueAt(linha, 2));
        cliente.setTelefone((String) modelo.getValueAt(linha, 3));
        cliente.setEstadoCivil((String) modelo.getValueAt(linha, 4));
            
        return cliente;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscarCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscarCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscarCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscarCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscarCliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPeca;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExclur;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox cbBuscarTodas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JFormattedTextField tfCpf;
    // End of variables declaration//GEN-END:variables
}
