/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Peça;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rogério e Octavio
 */
public class FormBuscarPeças extends javax.swing.JFrame {

    DefaultTableModel modelo;
    
        public FormBuscarPeças() {
        initComponents();
        
        this.modelo = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCodigo = new javax.swing.JTextField();
        btBuscarPeca = new javax.swing.JButton();
        cbBuscarTodas = new javax.swing.JCheckBox();
        lbCodigo = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btExclur = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Livros em Acervo");

        btBuscarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/wrench.png"))); // NOI18N
        btBuscarPeca.setText("Buscar Peça");
        btBuscarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPecaActionPerformed(evt);
            }
        });

        cbBuscarTodas.setForeground(new java.awt.Color(0, 0, 204));
        cbBuscarTodas.setText("Buscar todas");
        cbBuscarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarTodasActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código");

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/pencil.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/door_out.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btExclur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensProjeto/delete.png"))); // NOI18N
        btExclur.setText("Excluir");
        btExclur.setEnabled(false);
        btExclur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclurActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Descrição", "Fornecedor", "Qtde", "Valor Unitário", "Cadastrado em"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCodigo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(btBuscarPeca)
                                    .addGap(60, 60, 60)
                                    .addComponent(cbBuscarTodas)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEditar)
                                .addGap(109, 109, 109)
                                .addComponent(btExclur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSair)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPeca)
                    .addComponent(cbBuscarTodas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btSair)
                    .addComponent(btExclur))
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(784, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPecaActionPerformed
        // TODO add your handling code here:
        limparTabela();
        
        if(cbBuscarTodas.isSelected()){ // buscar todos os livros
            
            List<Peça> lista = FormPricipal.daoPeça.todosPeça();
            for(Peça p: lista){
                incluirPeca(p);
            }
        }
        else{ // buscar um so
            
            if(tfCodigo.getText().trim().length() != 0){
                
               String codigo = tfCodigo.getText();
                Peça peca = FormPricipal.daoPeça.buscarPeça(codigo);
                if(peca != null){
                    incluirPeca(peca);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Peça não encontrada", "Atenção", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Prencher o codigo", "Atenção", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btBuscarPecaActionPerformed

    private void cbBuscarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarTodasActionPerformed
        // TODO add your handling code here:
        if(cbBuscarTodas.isSelected()){
            tfCodigo.setEnabled(false);
        }
        else{
            tfCodigo.setEnabled(true);
            tfCodigo.requestFocus();
            tfCodigo.setText("");
        }
    }//GEN-LAST:event_cbBuscarTodasActionPerformed

    
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btExclurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclurActionPerformed
        // TODO add your handling code here:
        
        Peça peca = getPeca();
        FormPricipal.daoPeça.removerPeça(peca.getCodigo());
        
        modelo.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_btExclurActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        Peça peca = getPeca();
        
        FormPeças frm = new FormPeças();
        frm.setVisible(true);
        frm.peça = peca;
        this.dispose();
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        btEditar.setEnabled(true);
        btExclur.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void limparTabela(){
        for (int i = jTable1.getRowCount() - 1; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    private void incluirPeca(Peça peca){
        modelo.addRow(new Object[]{peca.getCodigo(), peca.getDescricao(), peca.getFornecedor(), peca.getEstoque(),
            peca.getValor(), peca.getDataCadastro()});
        
    }
    
    private Peça getPeca(){
        Peça peca = new Peça();
        int linha = jTable1.getSelectedRow();
        
        peca.setCodigo((String) modelo.getValueAt(linha, 0));
        peca.setDescricao((String) modelo.getValueAt(linha, 1));
        peca.setFornecedor((String) modelo.getValueAt(linha, 2));
        peca.setEstoque((Integer) modelo.getValueAt(linha, 3));
        peca.setValor((Float) modelo.getValueAt(linha, 4));
        peca.setDataCadastro((String) modelo.getValueAt(linha, 5));
        
        return peca;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscarPeças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscarPeças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscarPeças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscarPeças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscarPeças().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPeca;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExclur;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox cbBuscarTodas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JTextField tfCodigo;
    // End of variables declaration//GEN-END:variables
}
